GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/60a4caad0c9f58208e10eae5

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/60a4caad0c9f58208e10eae5

###

PATCH http://localhost:3000/subscribers/60a4caad0c9f58208e10eae5
Content-Type: application/json

{
    "name": "Gardo"
}